export { default as LandingPage } from './pages/LandingPage'
export { PropertyTypesSection } from './components/PropertyTypesSection'
export { NearbySection } from './components/NearbySection'
export { CitySection } from './components/CitySection'
export { PopularDestinations } from './components/PopularDestinations'
export { TrustBadgesSection } from './components/TrustBadgesSection'
export { TestimonialSection } from './components/TestimonialSection'
export { NewsletterSection } from './components/NewsletterSection'
export { PropertyCard } from './components/PropertyCard'
export { PropertySection } from './components/PropertySection'
